"""initial schema

Revision ID: a602b6610fd8
Revises: 
Create Date: 2026-02-27 17:27:12.560985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a602b6610fd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_atlas',
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('gcs_image_uri', sa.String(length=500), nullable=False),
    sa.Column('vertex_vector_id', sa.String(length=100), nullable=False),
    sa.Column('diagnosis_label', sa.String(length=255), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=50), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=False),
    sa.Column('source_dataset', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('reference_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PCP', 'PATIENT', name='userrole', native_enum=False), nullable=False),
    sa.Column('npi_number', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_resource', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_physician_id', sa.Integer(), nullable=False),
    sa.Column('mrn_internal', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_physician_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('mrn_internal')
    )
    op.create_index(op.f('ix_patients_primary_physician_id'), 'patients', ['primary_physician_id'], unique=False)
    op.create_table('clinical_images',
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('gcs_image_uri', sa.String(length=500), nullable=False),
    sa.Column('vertex_vector_id', sa.String(length=100), nullable=True),
    sa.Column('lesion_location', sa.String(length=255), nullable=False),
    sa.Column('clinician_notes', sa.String(length=2000), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_clinical_images_patient_id'), 'clinical_images', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_images_user_id'), 'clinical_images', ['user_id'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('feedback_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['clinical_images.query_id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['reference_atlas.reference_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('query_id', 'reference_id', 'user_id', name='uq_feedback_triple')
    )
    op.create_index(op.f('ix_recommendation_feedback_query_id'), 'recommendation_feedback', ['query_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_reference_id'), 'recommendation_feedback', ['reference_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_reference_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_query_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index(op.f('ix_clinical_images_user_id'), table_name='clinical_images')
    op.drop_index(op.f('ix_clinical_images_patient_id'), table_name='clinical_images')
    op.drop_table('clinical_images')
    op.drop_index(op.f('ix_patients_primary_physician_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reference_atlas')
    # ### end Alembic commands ###
